payload:
- DOMAIN-KEYWORD,shihuo
- DOMAIN-KEYWORD,taobao
- DOMAIN-KEYWORD,xiaohongshu
- DOMAIN-KEYWORD,xhs
- DOMAIN-KEYWORD,apple
- DOMAIN-KEYWORD,icloud
- DOMAIN-KEYWORD,bili
- DOMAIN-KEYWORD,163.com
- DOMAIN-KEYWORD,126.net
- DOMAIN-KEYWORD,qunar
- DOMAIN-KEYWORD,ximalaya
- DOMAIN-SUFFIX,xmcdn.com
- DOMAIN,upos-hz-mirrorakam.akamaized.net
- DOMAIN-SUFFIX,hdslb.com
