payload:
- DOMAIN-SUFFIX,xiaohongshu.com
- DOMAIN-SUFFIX,xhscdn.com
- DOMAIN-SUFFIX,apple.com
- DOMAIN-SUFFIX,icloud.com
- DOMAIN-SUFFIX,icloud-content.com
- DOMAIN-SUFFIX,bilibili.com
- DOMAIN-SUFFIX,bilistatic.cn
- DOMAIN-SUFFIX,bilivideo.com
- DOMAIN-SUFFIX,biliapi.com
- DOMAIN-SUFFIX,biliapi.net
- DOMAIN-SUFFIX,upos-hz-mirrorakam.akaimaized.net
- DOMAIN-SUFFIX,hdslb.com
- DOMAIN-SUFFIX,music.163.com
- DOMAIN-SUFFIX,music.126.net
- DOMAIN-SUFFIX,qunar.com
- DOMAIN-SUFFIX,ximalaya.com
- DOMAIN-SUFFIX,xmcdn.com
