payload:
# 小红书
- DOMAIN-SUFFIX,xiaohongshu.com
- DOMAIN-SUFFIX,xhscdn.com
- DOMAIN-SUFFIX,fegine.com

# Apple / iCloud
- DOMAIN-SUFFIX,cdn-apple.com
- DOMAIN-SUFFIX,apple.com
- DOMAIN-SUFFIX,icloud.com
- DOMAIN-SUFFIX,icloud-content.com
- DOMAIN-SUFFIX,mzstatic.com

# 哔哩哔哩
- DOMAIN-SUFFIX,bilibili.com
- DOMAIN-SUFFIX,bilistatic.cn
- DOMAIN-SUFFIX,bilivideo.com
- DOMAIN-SUFFIX,bilivideo.cn
- DOMAIN-SUFFIX,biliapi.com
- DOMAIN-SUFFIX,biliapi.net
- DOMAIN-SUFFIX,hdslb.com
- DOMAIN,upos-hz-mirrorakam.akamaized.net

# 网易
- DOMAIN-SUFFIX,163.com
- DOMAIN-SUFFIX,126.net
- DOMAIN-SUFFIX,127.net
- DOMAIN-SUFFIX,netease.com
- DOMAIN-SUFFIX,xinqiucc.com

# 去哪儿
- DOMAIN-SUFFIX,qunar.com

# 喜马拉雅
- DOMAIN-SUFFIX,ximalaya.com
- DOMAIN-SUFFIX,xmcdn.com

# 拼多多
- DOMAIN-SUFFIX,pinduoduo.com
- DOMAIN-SUFFIX,pdd.com
- DOMAIN-SUFFIX,yangkeduo.com
- DOMAIN-SUFFIX,pddpic.com

# 闲鱼 / 识货 / 淘宝(阿里系,支付除外)
- DOMAIN-SUFFIX,goofish.com
- DOMAIN-SUFFIX,shihuo.com
- DOMAIN-SUFFIX,taobao.com
- DOMAIN-SUFFIX,taobaocdn.com
- DOMAIN-SUFFIX,tmall.com
- DOMAIN-SUFFIX,alicdn.com
- DOMAIN-SUFFIX,mmstat.com

# 美团 / 大众点评
- DOMAIN-SUFFIX,meituan.com
- DOMAIN-SUFFIX,meituan.net
- DOMAIN-SUFFIX,dpfile.com
- DOMAIN-SUFFIX,dianping.com
- DOMAIN-SUFFIX,maoyan.com
- DOMAIN-SUFFIX,sankuai.com

# 京东
- DOMAIN-SUFFIX,jd.com
- DOMAIN-SUFFIX,360buyimg.com
- DOMAIN-SUFFIX,jdcloud.com
- DOMAIN-SUFFIX,jcloudcs.com
- DOMAIN-SUFFIX,jd.hk
- DOMAIN-SUFFIX,jddj.com

# Apple / iCloud
- IP-ASN,714
- IP-ASN,6185
# 哔哩哔哩
- IP-ASN,63828
- IP-ASN,140633
# 网易
- IP-ASN,45062
- IP-ASN,137263
# 淘宝 / 天猫 / 阿里 CDN
- IP-ASN,24429
- IP-ASN,37963
- IP-ASN,45102
- IP-ASN,134963
# 美团 / 大众点评
- IP-ASN,59025
- IP-ASN,63619
- IP-ASN,4811
