payload:
# Mylist 
- DOMAIN-KEYWORD,amazon
- DOMAIN-KEYWORD,walmart
- DOMAIN-KEYWORD,target
- DOMAIN-KEYWORD,homedepot
- DOMAIN-KEYWORD,thd
- DOMAIN-KEYWORD,lowes
- DOMAIN-KEYWORD,tractorsupply
- DOMAIN-KEYWORD,costco
- DOMAIN-KEYWORD,acehardware
- DOMAIN-KEYWORD,homehardware
- DOMAIN-KEYWORD,canadiantire
- DOMAIN-KEYWORD,rona
- DOMAIN-KEYWORD,menards
- DOMAIN-KEYWORD,samsclub
- DOMAIN-KEYWORD,bjs
- DOMAIN-KEYWORD,tjx
- DOMAIN-KEYWORD,burlington
- DOMAIN-KEYWORD,dollargeneral
- DOMAIN-KEYWORD,aldi
- DOMAIN-KEYWORD,gamestop
- DOMAIN-KEYWORD,staples
- DOMAIN-KEYWORD,bestbuy
- DOMAIN-KEYWORD,officedepot
- DOMAIN-KEYWORD,kroger

# OpenAI/ChatGPT
- DOMAIN-KEYWORD,openai
- DOMAIN-KEYWORD,chatgpt
- DOMAIN-SUFFIX,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net
- DOMAIN-SUFFIX,openaicomproductionae4b.blob.core.windows.net
- DOMAIN-SUFFIX,production-openaicom-storage.azureedge.net
- DOMAIN-SUFFIX,ai.com
- DOMAIN-SUFFIX,livekit.cloud
- DOMAIN-SUFFIX,oaistatic.com
- DOMAIN-SUFFIX,oaiusercontent.com
- DOMAIN-SUFFIX,imgix.net
- DOMAIN-SUFFIX,oai.com
- DOMAIN-SUFFIX,chat.com
- DOMAIN-SUFFIX,sora.com
- DOMAIN-SUFFIX,hcaptcha.com
- DOMAIN-SUFFIX,turnstile.cloudflare.com

# NotebookLM
- DOMAIN-KEYWORD,notebooklm
- DOMAIN-SUFFIX,notebooklm-pa.googleapis.com